### ISSUE TITLE
Spike on plugs/Phoenix

### ISSUE THREAD

**Issue by ZooeyMiller** [dwyl/elixir-auth-github#3]
We need to spike on how Plugs work in phoenix as we need to redirect to github as part of the Oauth flow.

**Comment by finnhodgkin** [comment]
https://hexdocs.pm/phoenix/plug.html#module-plugs

Module plugs look like they could work well for a simpler flow: 

The user provides an additional environment variable of `callback_url` and adds an elixir-auth-github plug to the router that watches for a conn containing the callback url. Once it catches the callback conn, the plug would run the normal `github_auth/1` / `github_auth/2` function and attach the returned data to the conn.

**Comment by nelsonic** [comment]
anyone learning about Elixir Plugs should follow: https://github.com/dwyl/elixir-plug-tutorial

We have built upon all of our knowledge of Plugs from several Elixir/Phoenix projects
and created a reusable Authentication Plug: https://github.com/dwyl/auth_plug

✅
