### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by SimonLab** [dwyl/elixir-auth-github#40]
Make sure the [httpoison](https://hex.pm/packages/httpoison) and [poison](https://hex.pm/packages/poison) are up to date and compatible.

If different packages use the same library some conflicts can occur when the version is different:
![image](https://user-images.githubusercontent.com/6057298/74013678-f4375880-4984-11ea-8acd-a1437902edcf.png)

**Comment by nelsonic** [comment]
@SimonLab If you haven't already made the updates to `mix.exs` and `.travis.yml` please see #41  👍

**Comment by nelsonic** [comment]
@SimonLab the latest versions of _both_ packages on Hex.pm is 1.0.3 with matching dependencies so there should no longer be any conflict. 🤞

**Comment by SimonLab** [comment]
New version can be found at https://hex.pm/packages/elixir_auth_github
![image](https://user-images.githubusercontent.com/6057298/74020861-58144e00-4992-11ea-8791-04fc982cd0cf.png)
