### ISSUE TITLE
Allow `login_url` to have a scope and state as parameters

### ISSUE THREAD

**Issue by SimonLab** [dwyl/elixir-auth-github#42]
The current `login_url` function can be used without any parameters or with a scope parameter:

https://github.com/dwyl/elixir-auth-github/blob/03f390baec154ddbe991671ff90337132ce42e92/lib/elixir_auth_github.ex#L19-L30

I propose that we update the `login_url` function so it accepts a map containing scope or state or both of the query parameters at the same time.

**Comment by nelsonic** [comment]
Included in PR #43 and `1.1.0` Published to Hex.pm :shipit:
