### ISSUE TITLE
Post to Github defaults to port 4000

### ISSUE THREAD

**Issue by ndrean** [dwyl/elixir-auth-github#62]
If I change the default port and run `PORT=4001 iex ...`, then the click button navigates to `localhost:4000/auth/github.callback...`

**Comment by nelsonic** [comment]
Hi @ndrean thanks very much for opening this issue to share your feedback. 🙌 

TCP Port `4000` is not hard-coded anywhere in the code: 
https://github.com/dwyl/elixir-auth-github/search?q=4000&type=code

My hunch is that you have defined `4000` in the Homepage URL when configuring your GItHub App: [Application Details](https://github.com/dwyl/elixir-auth-github/blob/f9448b8a9a45a519491520bca02ddc17c8917030/create-github-app-guide.md#2-define-the-details-for-your-application)

I don't know if there is a way to _dynamically_ change the port... you may need to update the GitHub App first. 💭 
Please keep us informed with your progress. 🙏 
We are _very_ keen to iron out any kinks. 👍

**Comment by nelsonic** [comment]
@SimonLab given that you are the person on the team with the most recent experience of using this package, ❤️ 
if you can help investigate after @ndrean has had a second look, please do. 🤞

**Comment by ndrean** [comment]
Ahh yes! Thank you @nelsonic for this answer. So the code is perfect :) The point is I need to test a distributed app.

**Comment by nelsonic** [comment]
@ndrean cool. Very happy to be your [Remote] [Rubber Duck Debugger](https://en.wikipedia.org/wiki/Rubber_duck_debugging). 😉 

![rubber-duc-debugging](https://upload.wikimedia.org/wikipedia/commons/d/d5/Rubber_duck_assisting_with_debugging.jpg)

Thanks for testing + using + _starring_ the package. 🤩 
If you have any issues with deployment, please let us know. 👍

**Comment by ndrean** [comment]
Thanks for sharing your code. Now since the redirection`localhost:4000` is hard-coded, I don't see how I run two nodes and reach them from my browser to test distributed mode.

**Comment by ndrean** [comment]
Yes, doing this, but unhappy doing this. Couldn't find any info on setting a dynamic url in Github.

**Comment by ndrean** [comment]
Found and tested something easy: [dotenv-parser](https://hexdocs.pm/dotenv_parser/DotenvParser.html). It does the trick! Just create a ".env" with the two keys, gitignore it and paste the lines below in "runtimes.exs". No more copy/pasting :) 
```elixir
config :elixir_auth_github,
  client_id: System.fetch_env!("GITHUB_CLIENT_ID"),
  client_secret: System.fetch_env!("GITHUB_CLIENT_SECRET")
```

**Comment by ndrean** [comment]
Very first try with Caddy to reverse proxy two load-balanced nodes reached at "localhost:5000" . I will dockerize a release (adopting Elixir!) and test your solution.
```go
5000 {
  reverse_proxy 127.0.0.1:4000 127.0.0.1:4001 {
    lb_policy round_robin
    
    header_up Host {host}
    header_up Host {upstream_hostport}
    header_up X-Real-IP {remote_host}
  }
  file_server
  encode zstd gzip

  log {
    output stdout
    format console
  }
}
```

**Comment by nelsonic** [comment]
https://github.com/caddyserver/caddy 👀
